### ISSUE TITLE
Command to delete user does not work the way the help says

### ISSUE THREAD

**Issue by laurentqro** [fabientownsend/lunchbot#104]
### What I expect

When I type `delete user: @makis`, I expect the Makis to be removed from the users table.

### What happens

Nothing happens. The user does not get deleted.

### Why this happens

This is because the command looks up users not by Slack handle but by full name.

### Suggested fix

We need to make sure we store users' Slack handle (`user_id`) in the users table so that we can look a user up by that value.

For inspiration, look at the set foreman command, that looks up by `user_id`: https://github.com/fabientownsend/lunchbot/blob/master/lib/commands/foreman/set_foreman.rb#L15.

**Comment by fabientownsend** [comment]
Fixed
