### ISSUE TITLE
New command for foreman setup

### ISSUE THREAD

**Issue by Gabbendorf** [fabientownsend/lunchbot#2]
To change foreman, currently there's only one option to change the current foreman with the next one in line on the list.
There should be a command for setting up a foreman directly from the list of foremen without having to repetitively change to next foreman until the correct one is found

**Comment by eatoncns** [comment]
Just to note that the way the next is done seems a bit weird as well. Could just replace entirely with the direct command.

**Comment by fabientownsend** [comment]
This feature exist
